# Generated by Django 5.2.8 on 2025-11-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_sharedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('scan', 'Scan Document'), ('audio', 'Audio')], max_length=20),
        ),
    ]
