# Generated by Django 4.2.7 on 2025-11-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('gmail', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('business_hours', models.CharField(blank=True, max_length=100)),
                ('services', models.TextField(blank=True)),
                ('social_links', models.JSONField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='profile_photos/')),
            ],
        ),
    ]
