# Generated by Django 5.2.8 on 2025-11-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Business", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
