# Generated by Django 6.0 on 2025-12-11 09:12

import Meeting.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_code', models.CharField(db_index=True, default=Meeting.models.generate_meeting_code, max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('max_participants', models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(300)])),
                ('duration_limit_minutes', models.IntegerField(default=180, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(1440)])),
                ('is_lobby_enabled', models.BooleanField(default=True)),
                ('is_recording_enabled', models.BooleanField(default=False)),
                ('is_chat_enabled', models.BooleanField(default=True)),
                ('is_screen_share_enabled', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('ended', 'Ended')], db_index=True, default='scheduled', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_start', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('file', 'File'), ('reaction', 'Reaction'), ('system', 'System')], default='text', max_length=20)),
                ('content', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='Meeting.meeting')),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_participants', models.IntegerField(default=0)),
                ('peak_participants', models.IntegerField(default=0)),
                ('average_participants', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('total_messages', models.IntegerField(default=0)),
                ('total_reactions', models.IntegerField(default=0)),
                ('total_hand_raises', models.IntegerField(default=0)),
                ('screen_shares_count', models.IntegerField(default=0)),
                ('average_connection_quality', models.CharField(blank=True, max_length=20)),
                ('disconnect_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='Meeting.meeting')),
            ],
            options={
                'db_table': 'meeting_analytics',
            },
        ),
        migrations.CreateModel(
            name='MeetingInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='Meeting.meeting')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_invitations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('host', 'Host'), ('co_host', 'Co-Host'), ('participant', 'Participant')], default='participant', max_length=20)),
                ('status', models.CharField(choices=[('lobby', 'In Lobby'), ('admitted', 'Admitted'), ('joined', 'Joined'), ('left', 'Left'), ('removed', 'Removed')], default='lobby', max_length=20)),
                ('is_audio_muted', models.BooleanField(default=False)),
                ('is_video_off', models.BooleanField(default=False)),
                ('is_hand_raised', models.BooleanField(default=False)),
                ('hand_raised_at', models.DateTimeField(blank=True, null=True)),
                ('is_screen_sharing', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('connection_quality', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20, null=True)),
                ('peer_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='Meeting.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_participants',
                'ordering': ['hand_raised_at', 'joined_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingReaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction_type', models.CharField(choices=[('thumbs_up', '👍'), ('thumbs_down', '👎'), ('heart', '❤️'), ('laugh', '😂'), ('clap', '👏'), ('celebrate', '🎉')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='Meeting.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_reactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField()),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('format', models.CharField(default='webm', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='recording', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='Meeting.meeting')),
                ('started_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meeting_recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['meeting_code'], name='meetings_meeting_b1add0_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['host', 'status'], name='meetings_host_id_362c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['scheduled_start'], name='meetings_schedul_e67e75_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['meeting', 'created_at'], name='chat_messag_meeting_5af7f4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender'], name='chat_messag_sender__e8b05b_idx'),
        ),
        migrations.AddIndex(
            model_name='meetinginvitation',
            index=models.Index(fields=['meeting', 'status'], name='meeting_inv_meeting_922e17_idx'),
        ),
        migrations.AddIndex(
            model_name='meetinginvitation',
            index=models.Index(fields=['email'], name='meeting_inv_email_cca3dd_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingparticipant',
            index=models.Index(fields=['meeting', 'status'], name='meeting_par_meeting_df9102_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingparticipant',
            index=models.Index(fields=['user'], name='meeting_par_user_id_025d70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingparticipant',
            unique_together={('meeting', 'user')},
        ),
        migrations.AddIndex(
            model_name='meetingreaction',
            index=models.Index(fields=['meeting', 'expires_at'], name='meeting_rea_meeting_c1a53c_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingrecording',
            index=models.Index(fields=['meeting'], name='meeting_rec_meeting_0d4211_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingrecording',
            index=models.Index(fields=['status'], name='meeting_rec_status_02bbc1_idx'),
        ),
    ]
