# Generated by Django 5.2.8 on 2025-11-28 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='action',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('ended', 'Ended')], max_length=20),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='call_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='video.callsession'),
        ),
        migrations.AlterField(
            model_name='callsession',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('ongoing', 'Ongoing'), ('ended', 'Ended'), ('missed', 'Missed')], default='initiated', max_length=20),
        ),
    ]
